openapi: 3.0.1
info:
  title: EPAO API
  version: 1.0.0
servers:
  - url: 'https://localhost:5001'
paths:
  /health:
    get:
      summary: Check Health of API
      description: Check Health of API
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/healthcheck'

  /ping:
    get:
      summary: Check API availability
      description: Check API availability
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                status: OK
                
  /api/epao/{id}:
    get:
      description: Get single End Point Aessement Oraganisation
      parameters:
        - name: id
          in: path
          description: ID of EPAO to use
          required: true
          schema:
            type: string
          style: simple
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/epao-organisation'
        '401':
          description: Not authenticated
          content: {}    
        '404':
          description: EPAO does not exist
          content: {}
      security:
        - bearer: []
      
  /api/epao:
    get:
      description: Get all End Point Aessement Oraganisations,
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/epao-organisation'
        '401':
          description: Not authenticated
          content: {}
      security:
        - bearer: []

  /api/courses/{id}/epao:
    get:
      description: Get End Point Aessement Oraganisations that provide a course by ID
      parameters:
        - name: id
          in: path
          description: Course ID to find EPAO's for
          required: true
          schema:
            type: string

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/epao-organisation'
        '401':
          description: Not authenticated
          content: {}
        '404':
          description: Course not found
          content: {}
      security:
        - bearer: []

components:
  schemas:
    epao-address:
      type: object
      properties:
        primary:
          type: string
        secondary:
          type: string
        street:
          type: string
        town:
          type: string
        postcode:
          type: string

    epao-organisation:
      type: object
      properties:
        epaOrganisation:
          type: string
        organisationType:
          type: string
        websiteLink:
          type: string
        epaOrganisationIdentifier:
          type: string
        email:
          type: string
        phone:
          type: string
        ukprn:
          type: integer
        address:
          $ref: '#/components/schemas/epao-address'

    healthcheck:
      type: object
      properties:
        status:
          type: string
        results:
          type: array
          items:
            $ref: '#/components/schemas/healthcheck-response'

    healthcheck-response:
      type: object
      properties:
        status: 
          type: string
        description: 
          type: string
        data:
          $ref: '#/components/schemas/healthcheck-data-response'

    healthcheck-data-response:
      type: object
      properties:
        duration:
          type: string

  securitySchemes:
    bearer:
      type: apiKey
      name: Authorization
      in: header