kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "mock-open-api-spec.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "mock-open-api-spec.labels" . | indent 4 }}
data:
  {{ (.Files.Glob "spec.yaml").AsConfig | indent 2 }}
