apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mock-open-api-spec.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "mock-open-api-spec.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mock-open-api-spec.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mock-open-api-spec.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "mock-open-api-spec.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            - /usr/local/bundle/bin/fakeit
            - --use-example
            - --static
            - --spec=/definitions/spec.yaml
          volumeMounts:
            - name: definitions
              mountPath: /definitions
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: definitions
          configMap:
            name: {{ include "mock-open-api-spec.fullname" . }}