{{- if .Values.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "mock-open-api-spec.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "mock-open-api-spec.labels" . | indent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/mocks/{{ .Release.Name }}`)
      kind: Rule
      middlewares:
        - name: secured
        - name: {{ include "mock-open-api-spec.fullname" . }}-repacepath-middleware
      services:
        - name: {{ include "mock-open-api-spec.fullname" . }}
          port: {{ .Values.service.port }}
  tls:
    secretName: {{ .Values.ingress.tls.SecretName }}
    options:
      name: enforce-tls-12
      namespace: {{ .Release.Namespace }}
{{- end }}