{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mock-open-api-spec.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "mock-open-api-spec.labels" . | indent 4 }}
{{- end -}}
